CREATE TABLE table_1 (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL
);

INSERT INTO table_1 (name) VALUES
('nbk'),
('hnn');


CREATE TABLE table_2 (
    id INTEGER PRIMARY KEY NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL
);

INSERT INTO table_2 (x, y) VALUES
(480, 847),
(440, 197);
